version: "3"
services:

  order-otel:
    depends_on:
      datadog-agent-otel:
        condition: service_started
    container_name: order-otel
    build:
      context: order
      dockerfile: Dockerfile
    environment:
      - DD_AGENT_HOST=datadog-agent-otel
      - DD_SERVICE=order
      - DD_ENV=otel-demo
      - DD_TRACE_OTEL_ENABLED=true
      - DD_TRACE_PROPAGATION_STYLE_INJECT=tracecontext
      - DD_TRACE_PROPAGATION_STYLE_EXTRACT=tracecontext
    ports:
      - "8081:8081"

  storage-otel:
    depends_on:
      datadog-agent-otel:
        condition: service_started
    container_name: storage-otel
    build:
      context: storage
      dockerfile: Dockerfile
    environment:
      - DD_AGENT_HOST=datadog-agent-otel
      - DD_SERVICE=storage
      - DD_ENV=otel-demo
      - DD_TRACE_OTEL_ENABLED=true
      - DD_TRACE_PROPAGATION_STYLE_INJECT=tracecontext
      - DD_TRACE_PROPAGATION_STYLE_EXTRACT=tracecontext
    ports:
      - "8080:8080"

  datadog-agent-otel:
    container_name: datadog-agent-otel
    image: "gcr.io/datadoghq/agent:latest"
    pid: host
    ports:
      - 8125:8125
      - 8126:8126
      - 4317:4317
      - 4318:4318
    environment:
      - DD_API_KEY
      - DD_SITE=datadoghq.eu
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT=0.0.0.0:4318
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro